// Copyright (c) 2015-2017. Spiracle Software. All Rights Reserved.

apply plugin: 'com.android.application'

android {
  compileSdkVersion 26
  buildToolsVersion "26.0.2"
  dexOptions {
    maxProcessCount 2
    javaMaxHeapSize "3g"
  }
  defaultConfig {
    applicationId "com.spiraclestudios.autoskola"
    minSdkVersion 16
    targetSdkVersion 26
    versionCode 13
    versionName "13"

    //renderscriptTargetApi 20
    //renderscriptSupportModeEnabled true

    // Disables generating PNGs at build time and uses real vectors instead.
    vectorDrawables.useSupportLibrary = true

    multiDexEnabled true
  }
  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }
  buildTypes {
    release {
      // TODO: Enable minification of release builds.
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
  }

  flavorDimensions "price"
  productFlavors {
    //noinspection GroovyMissingReturnStatement
    free {
      applicationId "com.spiraclestudios.autoskola"
      buildConfigField "boolean", "PREMIUM", "false"
    }
    //noinspection GroovyMissingReturnStatement
    premium {
      applicationId "com.spiraclestudios.autoskola.premium"
      buildConfigField "boolean", "PREMIUM", "true"
      /*
      if (BuildConfig.PREMIUM) {
          ...
      }
      */
      //manifestPlaceholders = [someApiKey: "key_here"]
      //use in manifest file like so "${someApiKey}"
    }
  }
  sourceSets {
    main {
      assets.srcDirs = ['src/main/assets', 'src/main/assets/']
      java.srcDirs = ['src/main/java']
    }
    //main.java.srcDirs += 'src/main/kotlin'
    free {
      java.srcDirs = ['src/free/java']
    }
    premium {
      java.srcDirs = ['src/premium/java']
    }
  }
  dataBinding {
    enabled = true
  }
}

repositories {
  maven { url 'https://maven.fabric.io/public' }
  mavenCentral()
  mavenLocal()
}

buildscript {
  repositories {
    maven { url 'https://maven.fabric.io/public' }
    jcenter()
    mavenCentral()
  }

  dependencies {
    //noinspection GradleDynamicVersion
    classpath 'io.fabric.tools:gradle:1.+'
    classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    //classpath Deps.kotlinPlugin
  }
}

//apply plugin: 'kotlin-android'
apply plugin: 'io.fabric'

dependencies {
  implementation fileTree(include: ['*.jar'], dir: 'libs')

  // Framework
  implementation project(path: ":framework-release")
  //debugImplementation project(path: deps.framework, configuration: "debug")
  //releaseImplementation project(path: deps.framework, configuration: "release")

  //implementation Deps.kotlinRuntime

  // Support Library
  implementation Deps.supportAppCompat
  implementation Deps.supportV4
  implementation Deps.supportV13
  implementation Deps.supportDesign
  implementation Deps.supportRecyclerView
  implementation Deps.supportCardView
  implementation Deps.supportGridLayout
  //implementation Deps.supportConstraintLayout

  // Firebase
  //implementation Deps.firebaseCore
  implementation Deps.firebaseAnalytics
  implementation Deps.firebaseAds
  //implementation Deps.firebaseInvites

  // Fabric
  implementation(Deps.crashlytics) { transitive = true }
  implementation(Deps.fabricAnswers) { transitive = true }

  // Leak Canary
  debugImplementation Deps.leakCanary
  releaseImplementation Deps.leakCanaryNoOp

  // Fast Adapter
  implementation(Deps.fastAdapter) { transitive = true; }
  implementation Deps.fastAdapterCommons
  //implementation Deps.fastAdapterExtensions

  // Butter Knife
  implementation Deps.butterknife
  annotationProcessor Deps.butterknifeAnnotations

  // Other
  implementation Deps.stetho
  implementation Deps.guava
  implementation Deps.timber
  implementation Deps.connectionbuddy
  implementation Deps.glide
  implementation Deps.multidex
  implementation(Deps.aboutLibraries) { transitive = true }
}

apply plugin: 'com.google.gms.google-services'
