// Copyright (c) 2015-2017. Spiracle Software. All Rights Reserved.

apply plugin: 'com.android.application'

android {
  compileSdkVersion 25
  buildToolsVersion "25.0.2"
  dexOptions {
    maxProcessCount 2
    javaMaxHeapSize "3g"
  }
  defaultConfig {
    applicationId "com.spiraclestudios.autoskola"
    minSdkVersion 16
    targetSdkVersion 24
    versionCode 10
    versionName "10"

    renderscriptTargetApi 20
    renderscriptSupportModeEnabled true

    // Disables generating PNGs at build time and uses real vectors instead.
    vectorDrawables.useSupportLibrary = true

    multiDexEnabled true
  }
  buildTypes {
    release {
      // TODO: Enable minification of release builds.
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
  }
  productFlavors {
    //noinspection GroovyMissingReturnStatement
    free {
      applicationId "com.spiraclestudios.autoskola"
      buildConfigField "boolean", "PREMIUM", "false"
    }
    //noinspection GroovyMissingReturnStatement
    premium {
      applicationId "com.spiraclestudios.autoskola.premium"
      buildConfigField "boolean", "PREMIUM", "true"
      /*
      if (BuildConfig.PREMIUM) {
          ...
      }
      */
      //manifestPlaceholders = [someApiKey: "key_here"]
      //use in manifest file like so "${someApiKey}"
    }
  }
  sourceSets {
    main {
      assets.srcDirs = ['src/main/assets', 'src/main/assets/']
      java.srcDirs = ['src/main/java']
    }
    //main.java.srcDirs += 'src/main/kotlin'
    free {
      java.srcDirs = ['src/free/java']
    }
    premium {
      java.srcDirs = ['src/premium/java']
    }
  }
  dataBinding {
    enabled = true
  }
}

repositories {
  maven { url 'https://maven.fabric.io/public' }
  mavenCentral()
  mavenLocal()
}

buildscript {
  tasks.withType(JavaCompile) {
    sourceCompatibility = JavaVersion.VERSION_1_7
    targetCompatibility = JavaVersion.VERSION_1_7
  }

  //ext.kotlin_version = '1.0.6'
  repositories {
    maven { url 'https://maven.fabric.io/public' }
    jcenter()
    mavenCentral()
  }

  dependencies {
    //noinspection GradleDynamicVersion
    classpath 'io.fabric.tools:gradle:1.+'
    classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
    //classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
  }
}

//apply plugin: 'kotlin-android'
apply plugin: 'io.fabric'

dependencies {
  compile fileTree(include: ['*.jar'], dir: 'libs')

  //compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

  // Leak Canary
  debugCompile 'com.squareup.leakcanary:leakcanary-android:1.3.1'
  releaseCompile 'com.squareup.leakcanary:leakcanary-android-no-op:1.3.1'

  // Fast Adapter
  compile('com.mikepenz:fastadapter:1.2.2@aar') { transitive = true; }
  //compile 'com.mikepenz:fastadapter-extensions:1.2.2@aar'

  // Firebase
  //compile 'com.google.firebase:firebase-core:9.0.2'
  compile 'com.google.firebase:firebase-analytics:9.0.2'
  compile 'com.google.firebase:firebase-ads:9.0.2'
  //compile "com.google.firebase:firebase-invites:9.0.2"

  // Fabric
  compile('com.crashlytics.sdk.android:crashlytics:2.6.6@aar') { transitive = true; }
  compile('com.crashlytics.sdk.android:answers:1.3.7@aar') { transitive = true; }

  // Support Library
  compile 'com.android.support:support-v4:25.1.1'
  compile 'com.android.support:appcompat-v7:25.1.1'
  compile 'com.android.support:support-v13:25.1.1'
  compile 'com.android.support:design:25.1.1'
  compile 'com.android.support:recyclerview-v7:25.1.1'
  compile 'com.android.support:cardview-v7:25.1.1'

  // Other
  compile 'com.android.support:multidex:1.0.1'
  compile 'com.google.guava:guava:19.0'
  compile 'com.jakewharton:butterknife:7.0.1'
  compile 'com.jakewharton.timber:timber:4.1.0'
  compile 'com.zplesac:connectionbuddy:1.4.0@aar'
  compile 'com.github.bumptech.glide:glide:3.7.0'
  compile 'com.facebook.stetho:stetho:1.4.1'
}

apply plugin: 'com.google.gms.google-services'
