# Copyright (c) 2015-2017. Spiracle Software. All Rights Reserved.

#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Thu Nov 05 14:29:18 CET 2015
apiSecret=6bd0139c55a90717f385dbb7d9b026c8d03b65ccf01ebd6e933063f60514d447
